### ISSUE TITLE
401 error

### ISSUE THREAD

**Issue by monsieurlatte** [nberardi/scrypted-dyson#2]
Trying to migrate my install over from homebridge to scrypted, when I put in my username and password I get 401 error.  Is there anyway to set this up with just using a known local password?  I already have one for my previous install.

[Status 401 Unauthorized] Unable to authenticate user.
aborting, authorization header not provided

**Comment by nberardi** [comment]
There is no ability to setup individual devices right now. It is something
I am exploring. If you are receiving a 401, make sure you log out of the
current Dyson app.

**Comment by monsieurlatte** [comment]
I have signed my iOS device out over 3 hours ago and still not working. Only other setup I have is using local auth.  Oh well thanks for replying!On Nov 27, 2022, at 6:40 PM, Nick Berardi ***@***.***> wrote:﻿
There is no ability to setup individual devices right now. It is something
I am exploring. If you are receiving a 401, make sure you log out of the
current Dyson app.

**Comment by nberardi** [comment]
Can you share the output from the console? Sent from my iPhone, expect autocorrection issuesOn Nov 27, 2022, at 6:46 PM, monsieurlatte ***@***.***> wrote:﻿
I have signed my iOS device out over 3 hours ago and still not working. Only other setup I have is using local auth.  Oh well thanks for replying!On Nov 27, 2022, at 6:40 PM, Nick Berardi ***@***.***> wrote:﻿
There is no ability to setup individual devices right now. It is something
I am exploring. If you are receiving a 401, make sure you log out of the
current Dyson app.

**Comment by monsieurlatte** [comment]
server version: 0.4.1
plugin version: scrypted-dyson 0.1.4
plugin loaded
[Status 401 Unauthorized] Unable to authenticate user.
aborting, authorization header not provided

**Comment by monsieurlatte** [comment]
I may be way off key here since I dont know the first thing about coding, but here’s a link to the homebridge dyson setup that uses local authentication if that helps you at all in the future.

https://github.com/lukasroegner/homebridge-dyson-pure-cool#readme￼
lukasroegner/homebridge-dyson-pure-cool: Plugin for using the Dyson Pure Cool fans in homebridge.
github.com

**Comment by nberardi** [comment]
Once the devices are discovered in the cloud they authenticate using the
same approach. The limitation is that Scryted doesn’t provide a way to
create individual devices. The authentication would work the same way it
does in Homebridge if they provided that capability.

**Comment by monsieurlatte** [comment]
Ah gotcha. Any ideas on the authentication header issue I have?On Nov 30, 2022, at 10:23 AM, Nick Berardi ***@***.***> wrote:﻿
Once the devices are discovered in the cloud they authenticate using the
same approach. The limitation is that Scryted doesn’t provide a way to
create individual devices. The authentication would work the same way it
does in Homebridge if they provided that capability.

**Comment by nberardi** [comment]
Please check out the 0.2.0 version. It should allow you to take the `ipAddress`, `serialNumber`, and `credentials` you already have in Homebridge and setup the devices manually.

**Comment by monsieurlatte** [comment]
whoa, fast work on that! I took all my info from homebridge (disabled the plugin in there and rebooted the fan just to be sure) but I am seeing this in the console.

plugin version: scrypted-dyson 0.2.0
connecting to : mqtt://10.0.0.13
MQTT error: Error: Connection refused: Bad username or password
MQTT offline.
MQTT disconnected.
MQTT reconnecting.
MQTT error: Error: Connection refused: Bad username or password
MQTT disconnected.
MQTT reconnecting.
MQTT error: Error: Connection refused: Bad username or password
MQTT disconnected.
MQTT reconnecting.
MQTT error: Error: Connection refused: Bad username or password
MQTT disconnected.

**Comment by nberardi** [comment]
I have an idea of what’s going on, I will need to publish a new update with the changes.

**Comment by nberardi** [comment]
I forgot the `credentials` was a JSON object. Remove the devices you created and update to the latest v0.2.1 version and enter the IP Address and the Credentials into the `Homebridge Credentials` field.  You should be good to go after that.

**Comment by monsieurlatte** [comment]
Yep that worked!  I chose the dyson 475 (not sure how to figure out the model numbers from your dropdown but from a google search it seemed that maybe it was what I had.  I have the TP02 (ignore this saw you had them listed in the readme).  All works!!!!  You have anyway to take a buy me a coffee donation?

**Comment by monsieurlatte** [comment]
One more note (and not a deal breaker) the air quality sensor goes from reading something to unknown a lot and finally the percentage when the fan is set to auto doesn't appear to update, the plugin shows it as whatever it was at when you turned on auto feature but as auto changes from 01-10 plugin always says the previous setting.

**Comment by nberardi** [comment]
@monsieurlatte I should advertise [my buymeacoffee link](https://www.buymeacoffee.com/nberardi), any donations are more than welcome.  

Regarding the air quality sensor, that is a bug I am still tracking down the root cause. It appears to be a bug between the Dyson plugin and the HomeKit integration. I should have time in the next week or so to focus on it, as it is annoying me too.  :)

**Comment by nberardi** [comment]
@monsieurlatte I found the issue, I was accidentally trigging the code to send Unknown before setting the real value.  Please updated to release v0.2.2.

I am going to resolve this issue for now since the original 401 issue was worked around with manual device creation.

**Comment by monsieurlatte** [comment]
Wonderful!  Thanks so much, have a wonderful holiday!
